module.exports = {
  COLOR_RED: 'r',
  COLOR_BLUE: 'b',
  COLOR_YELLOW: 'y',
  COLOR_GREEN: 'g',
  COLOR_ESPECIAL: 's',
  MAX_PLAYERS_ROOM: 4,
  MIN_PLAYERS_ROOM: 1,
  INITIAL_CARDS_PLAYER: 7,
  VALUE_SKIP: 'b',
  VALUE_REVERTE: 't',
  VALUE_M2: 'm2',
  VALUE_JOCKER: 's1',
  VALUE_M4: 'm4',
  CLOCKWISE: 1,
  ANTICLOCKWISE: -1,
  POINTS_WINER: 500
};
